services:
  budka-psn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budka-psn-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
